inherit_from: .rubocop_todo.yml

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

AllCops:
  Exclude:
    - '/spec/factories/*.rb'
    - 'spec/models/*.rb'
    - 'spec/requests/*.rb'
